/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AboutNumbers {
    #[serde(rename = "predictions")]
    pub predictions: i32,
    #[serde(rename = "questions")]
    pub questions: i32,
    #[serde(rename = "resolved_questions")]
    pub resolved_questions: i32,
    #[serde(rename = "years_of_predictions")]
    pub years_of_predictions: i32,
}

impl AboutNumbers {
    #[must_use]
    pub fn new(
        predictions: i32,
        questions: i32,
        resolved_questions: i32,
        years_of_predictions: i32,
    ) -> AboutNumbers {
        AboutNumbers {
            predictions,
            questions,
            resolved_questions,
            years_of_predictions,
        }
    }
}
