/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalCpReminder {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "delta")]
    pub delta: i32,
}

impl GlobalCpReminder {
    #[must_use]
    pub fn new(enabled: bool, delta: i32) -> GlobalCpReminder {
        GlobalCpReminder { enabled, delta }
    }
}
