/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedUserProfile {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "bio_html", skip_serializing_if = "Option::is_none")]
    pub bio_html: Option<String>,
    #[serde(rename = "bio_text", skip_serializing_if = "Option::is_none")]
    pub bio_text: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
}

impl Default for PatchedUserProfile {
    fn default() -> Self {
        Self::new()
    }
}

impl PatchedUserProfile {
    #[must_use]
    pub fn new() -> PatchedUserProfile {
        PatchedUserProfile {
            id: None,
            url: None,
            bio_html: None,
            bio_text: None,
            website: None,
        }
    }
}
