/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionVote {
    #[serde(rename = "value")]
    pub value: crate::models::ValueEnum,
}

impl QuestionVote {
    #[must_use]
    pub fn new(value: crate::models::ValueEnum) -> QuestionVote {
        QuestionVote { value }
    }
}
