/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuestionUpdateStatusEnum {
    #[serde(rename = "V")]
    V,
    #[serde(rename = "I")]
    I,
    #[serde(rename = "T")]
    T,
}

impl ToString for QuestionUpdateStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::V => String::from("V"),
            Self::I => String::from("I"),
            Self::T => String::from("T"),
        }
    }
}

impl Default for QuestionUpdateStatusEnum {
    fn default() -> QuestionUpdateStatusEnum {
        Self::V
    }
}
