/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionSummaryFeedback {
    #[serde(rename = "question_id")]
    pub question_id: i32,
    #[serde(rename = "summary_id")]
    pub summary_id: i32,
    #[serde(rename = "summary_timestamp")]
    pub summary_timestamp: String,
    #[serde(rename = "comment")]
    pub comment: String,
}

impl QuestionSummaryFeedback {
    #[must_use]
    pub fn new(
        question_id: i32,
        summary_id: i32,
        summary_timestamp: String,
        comment: String,
    ) -> QuestionSummaryFeedback {
        QuestionSummaryFeedback {
            question_id,
            summary_id,
            summary_timestamp,
            comment,
        }
    }
}
