/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionSummary {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "question_id")]
    pub question_id: i32,
    #[serde(rename = "content")]
    pub content: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl QuestionSummary {
    #[must_use]
    pub fn new(
        id: i32,
        question_id: i32,
        content: ::std::collections::HashMap<String, serde_json::Value>,
        timestamp: String,
    ) -> QuestionSummary {
        QuestionSummary {
            id,
            question_id,
            content,
            timestamp,
        }
    }
}
