/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReminderStatusEnum {
    #[serde(rename = "REMINDER_STATUS_ACTIVE")]
    Active,
    #[serde(rename = "REMINDER_STATUS_SENT")]
    Sent,
    #[serde(rename = "REMINDER_STATUS_DEACTIVATED")]
    Deactivated,
}

impl ToString for ReminderStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Active => String::from("REMINDER_STATUS_ACTIVE"),
            Self::Sent => String::from("REMINDER_STATUS_SENT"),
            Self::Deactivated => String::from("REMINDER_STATUS_DEACTIVATED"),
        }
    }
}

impl Default for ReminderStatusEnum {
    fn default() -> ReminderStatusEnum {
        Self::Active
    }
}
