/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScoreTypeEnum {
    #[serde(rename = "LEGACY")]
    Legacy,
    #[serde(rename = "ABS_LOG")]
    AbsLog,
}

impl ToString for ScoreTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Legacy => String::from("LEGACY"),
            Self::AbsLog => String::from("ABS_LOG"),
        }
    }
}

impl Default for ScoreTypeEnum {
    fn default() -> ScoreTypeEnum {
        Self::Legacy
    }
}
