/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShareQuestion {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "username")]
    pub username: String,
}

impl ShareQuestion {
    #[must_use]
    pub fn new(message: String, id: i32, username: String) -> ShareQuestion {
        ShareQuestion {
            message,
            id,
            username,
        }
    }
}
