/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status3baEnum {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "T")]
    T,
    #[serde(rename = "I")]
    I,
    #[serde(rename = "R")]
    R,
    #[serde(rename = "D")]
    D,
    #[serde(rename = "V")]
    V,
}

impl ToString for Status3baEnum {
    fn to_string(&self) -> String {
        match self {
            Self::A => String::from("A"),
            Self::T => String::from("T"),
            Self::I => String::from("I"),
            Self::R => String::from("R"),
            Self::D => String::from("D"),
            Self::V => String::from("V"),
        }
    }
}

impl Default for Status3baEnum {
    fn default() -> Status3baEnum {
        Self::A
    }
}
