/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "levelTitle")]
    pub level_title: String,
    #[serde(rename = "date_joined")]
    pub date_joined: String,
    #[serde(rename = "supporter_level")]
    pub supporter_level: i32,
    #[serde(rename = "supporter_since")]
    pub supporter_since: String,
    #[serde(rename = "formerly_known_as")]
    pub formerly_known_as: String,
}

impl User {
    #[must_use]
    pub fn new(
        id: i32,
        url: String,
        username: String,
        level: i32,
        level_title: String,
        date_joined: String,
        supporter_level: i32,
        supporter_since: String,
        formerly_known_as: String,
    ) -> User {
        User {
            id,
            url,
            username,
            level,
            level_title,
            date_joined,
            supporter_level,
            supporter_since,
            formerly_known_as,
        }
    }
}
