/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserProfile {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "bio_html")]
    pub bio_html: String,
    #[serde(rename = "bio_text", skip_serializing_if = "Option::is_none")]
    pub bio_text: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
}

impl UserProfile {
    #[must_use]
    pub fn new(id: i32, url: String, bio_html: String) -> UserProfile {
        UserProfile {
            id,
            url,
            bio_html,
            bio_text: None,
            website: None,
        }
    }
}
