/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserFeedback {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "text_input")]
    pub text_input: String,
}

impl UserFeedback {
    #[must_use]
    pub fn new(url: String, text_input: String) -> UserFeedback {
        UserFeedback { url, text_input }
    }
}
