/*
 * Metaculus API
 *
 * Welcome to the unofficial Rust client for the Metaculus API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Benjamin Manns <opensource@benmanns.com>
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserCommunityVisEnum {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "-1")]
    Variant1,
    #[serde(rename = "1")]
    Variant12,
}

impl ToString for UserCommunityVisEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Variant0 => String::from("0"),
            Self::Variant1 => String::from("-1"),
            Self::Variant12 => String::from("1"),
        }
    }
}

impl Default for UserCommunityVisEnum {
    fn default() -> UserCommunityVisEnum {
        Self::Variant0
    }
}
